### ISSUE TITLE
[feat] Seção para baixar o App

### ISSUE THREAD

**Issue by talDoFlemis** [ceos-jr/jeronimo#7]
# **🚀 Nova Feature**

## **A sua feature é relacionada com algum problema?. Por favor descreva**

Gostaria que existisse uma seção no site que apresentasse um link para baixar nosso app

## **Descreva uma solução que você gostaria que acontecesse**

Teria uma texto simples com um fundo de restaurante e um botão para baixar o app
![image](https://user-images.githubusercontent.com/33133120/211032205-73a94650-43fb-41eb-ae7d-95713ae3ded0.png)

**Comment by en20** [comment]
dia 09 ---> assigned

**Comment by talDoFlemis** [comment]
> dia 09 ---> assigned

n precisa falar isso não enzola, ja ta registrado meu men
